queues:
  # source → transform_a, transform_b
  # 1 producer (source), 2 competing consumers (load-balanced)
  # NOTE: records are NOT broadcast/duplicated to both consumers.
  - name: q_in
    capacity: 512

  # transform_a → sink_a
  # 1 producer, 1 consumer
  - name: q_a
    capacity: 256

  # transform_b → sink_b
  # 1 producer, 1 consumer
  - name: q_b
    capacity: 256

stages:
  - name: source
    type: noop_source
    threads: 1
    output_queue: q_in
    config:
      delay_ms: 200
      message: "FOOBAR"
      max_messages: 20

  - name: transform_a
    type: noop_transform
    threads: 1
    input_queue: q_in
    output_queue: q_a
    config:
      verbose: true
      delay_ms: 10

  - name: transform_b
    type: noop_transform
    threads: 1
    input_queue: q_in
    output_queue: q_b
    config:
      verbose: false
      delay_ms: 50

  - name: sink_a
    type: stdout_sink
    threads: 1
    input_queue: q_a

  - name: sink_b
    type: stdout_sink
    threads: 1
    input_queue: q_b
