name: noop-observability-k3s
runtime: FLOW_RUNTIME_BUILTIN
image: ghcr.io/hurdad/flow-pipe-runtime:main-ubuntu24.04
execution:
  mode: EXECUTION_MODE_STREAMING
queues:
  - name: q1
    capacity: 128
stages:
  - name: src
    type: noop_source
    threads: 1
    output_queue: q1
    config:
      delay_ms: 200
      message: "DEADBEEF"
      max_messages: 0
  - name: sink
    type: stdout_sink
    threads: 1
    input_queue: q1
observability:
  metrics_enabled: true
  tracing_enabled: true
  logs_enabled: true