name: noop-observability-k3s
execution:
  mode: EXECUTION_MODE_STREAMING
kubernetes:
  image: ghcr.io/hurdad/flow-pipe-runtime:main-ubuntu24.04
  image_pull_policy: IMAGE_PULL_POLICY_ALWAYS
  restart_policy: RESTART_POLICY_ALWAYS
kubernetes_options:
  streaming_workload_kind: STREAMING_WORKLOAD_KIND_DEPLOYMENT
queues:
  - name: q1
    capacity: 128
stages:
  - name: src
    type: noop_source
    threads: 1
    output_queue: q1
    config:
      delay_ms: 1000
      message: "FOOBAR"
      max_messages: 0
  - name: sink
    type: stdout_sink
    threads: 1
    input_queue: q1
observability:
  metrics_enabled: true
  metrics:
    stage_metrics_disabled: false
    queue_metrics_disabled: false
    flow_metrics_disabled: false
    latency_histograms_disabled: false
  tracing_enabled: true
  logs_enabled: false
  debug: true
