queues:
  # source → transform
  # 1 producer (source), 2 consumers (transform threads)
  - name: q1
    type: QUEUE_TYPE_MPMC
    capacity: 256

  # transform → sink
  # 2 producers (transform threads), 1 consumer (sink)
  - name: q2
    type: QUEUE_TYPE_MPSC
    capacity: 256

stages:
  - name: source
    type: noop_source
    threads: 1
    output_queue: q1

  - name: transform
    type: noop_transform
    threads: 2
    input_queue: q1
    output_queue: q2

  - name: sink
    type: stdout_sink
    threads: 1
    input_queue: q2
